export const claimTemplate = {
    "Id": 0,
    "Name": "CLAIM TEMPLATE",
    "ClientCompanyId": 1,
    "ClientCompany": null,
    "InsuranceType": 0,
    "LocationTemplate": [
      {
        "Id": 0,
        "LocationName": "VERIFIER_ADDRESS",
        "AgentId": 1,
        "Agent": {
          "DigitalIdImageMatchConfidence": "",
          "Similarity": 0,
          "Has2Face": false,
          "IdImageValid": false,
          "ReportType": 0,
          "Id": 0,
          "Selected": false,
          "IdIName": null,
          "IdImage": null,
          "IdImageData": "No Location Info...",
          "IdImageLocationUrl": null,
          "Distance": null,
          "DistanceInMetres": null,
          "Duration": null,
          "DurationInSeconds": null,
          "IdImageLocationAddress": "No Address data",
          "IdImageLongLat": null,
          "IdImageLongLatTime": null,
          "ValidationExecuted": false,
          "Created": "2025-04-28T23:50:08.468375+10:00",
          "IsUpdated": true,
          "Updated": null,
          "CreatedUser": "--",
          "UpdatedBy": "--"
        },
        "FaceIds": [
          {
            "DigitalIdImageMatchConfidence": "",
            "Similarity": 0,
            "Has2Face": false,
            "IdImageValid": false,
            "ReportType": 1,
            "Id": 0,
            "Selected": false,
            "IdIName": "CUSTOMER_PHOTO",
            "IdImage": null,
            "IdImageData": "No Location Info...",
            "IdImageLocationUrl": null,
            "Distance": null,
            "DistanceInMetres": null,
            "Duration": null,
            "DurationInSeconds": null,
            "IdImageLocationAddress": "No Address data",
            "IdImageLongLat": null,
            "IdImageLongLatTime": null,
            "ValidationExecuted": false,
            "Created": "2025-04-28T23:50:08.4695236+10:00",
            "IsUpdated": true,
            "Updated": null,
            "CreatedUser": "--",
            "UpdatedBy": "--"
          },
          {
            "DigitalIdImageMatchConfidence": "",
            "Similarity": 0,
            "Has2Face": false,
            "IdImageValid": false,
            "ReportType": 2,
            "Id": 0,
            "Selected": false,
            "IdIName": "AGENT_CUSTOMER_PHOTO",
            "IdImage": null,
            "IdImageData": "No Location Info...",
            "IdImageLocationUrl": null,
            "Distance": null,
            "DistanceInMetres": null,
            "Duration": null,
            "DurationInSeconds": null,
            "IdImageLocationAddress": "No Address data",
            "IdImageLongLat": null,
            "IdImageLongLatTime": null,
            "ValidationExecuted": false,
            "Created": "2025-04-28T23:50:08.4698377+10:00",
            "IsUpdated": true,
            "Updated": null,
            "CreatedUser": "--",
            "UpdatedBy": "--"
          },
          {
            "DigitalIdImageMatchConfidence": "",
            "Similarity": 0,
            "Has2Face": false,
            "IdImageValid": false,
            "ReportType": 1,
            "Id": 0,
            "Selected": false,
            "IdIName": "BENEFICIARY_PHOTO",
            "IdImage": null,
            "IdImageData": "No Location Info...",
            "IdImageLocationUrl": null,
            "Distance": null,
            "DistanceInMetres": null,
            "Duration": null,
            "DurationInSeconds": null,
            "IdImageLocationAddress": "No Address data",
            "IdImageLongLat": null,
            "IdImageLongLatTime": null,
            "ValidationExecuted": false,
            "Created": "2025-04-28T23:50:08.4698401+10:00",
            "IsUpdated": true,
            "Updated": null,
            "CreatedUser": "--",
            "UpdatedBy": "--"
          },
          {
            "DigitalIdImageMatchConfidence": "",
            "Similarity": 0,
            "Has2Face": false,
            "IdImageValid": false,
            "ReportType": 2,
            "Id": 0,
            "Selected": false,
            "IdIName": "AGENT_BENEFICIARY_PHOTO",
            "IdImage": null,
            "IdImageData": "No Location Info...",
            "IdImageLocationUrl": null,
            "Distance": null,
            "DistanceInMetres": null,
            "Duration": null,
            "DurationInSeconds": null,
            "IdImageLocationAddress": "No Address data",
            "IdImageLongLat": null,
            "IdImageLongLatTime": null,
            "ValidationExecuted": false,
            "Created": "2025-04-28T23:50:08.4698446+10:00",
            "IsUpdated": true,
            "Updated": null,
            "CreatedUser": "--",
            "UpdatedBy": "--"
          }
        ],
        "DocumentIds": [
          {
            "IdImageBack": null,
            "HasBackImage": true,
            "DocumentIdImageValid": false,
            "DocumentIdReportType": 5,
            "Id": 0,
            "Selected": false,
            "IdIName": "DEATH_CERTIFICATE",
            "IdImage": null,
            "IdImageData": "No Location Info...",
            "IdImageLocationUrl": null,
            "Distance": null,
            "DistanceInMetres": null,
            "Duration": null,
            "DurationInSeconds": null,
            "IdImageLocationAddress": "No Address data",
            "IdImageLongLat": null,
            "IdImageLongLatTime": null,
            "ValidationExecuted": false,
            "Created": "2025-04-28T23:50:08.470439+10:00",
            "IsUpdated": true,
            "Updated": null,
            "CreatedUser": "--",
            "UpdatedBy": "--"
          },
          {
            "IdImageBack": null,
            "HasBackImage": true,
            "DocumentIdImageValid": false,
            "DocumentIdReportType": 0,
            "Id": 0,
            "Selected": false,
            "IdIName": "ADHAAR",
            "IdImage": null,
            "IdImageData": "No Location Info...",
            "IdImageLocationUrl": null,
            "Distance": null,
            "DistanceInMetres": null,
            "Duration": null,
            "DurationInSeconds": null,
            "IdImageLocationAddress": "No Address data",
            "IdImageLongLat": null,
            "IdImageLongLatTime": null,
            "ValidationExecuted": false,
            "Created": "2025-04-28T23:50:08.4709019+10:00",
            "IsUpdated": true,
            "Updated": null,
            "CreatedUser": "--",
            "UpdatedBy": "--"
          },
          {
            "IdImageBack": null,
            "HasBackImage": true,
            "DocumentIdImageValid": false,
            "DocumentIdReportType": 2,
            "Id": 0,
            "Selected": false,
            "IdIName": "DRIVING_LICENSE",
            "IdImage": null,
            "IdImageData": "No Location Info...",
            "IdImageLocationUrl": null,
            "Distance": null,
            "DistanceInMetres": null,
            "Duration": null,
            "DurationInSeconds": null,
            "IdImageLocationAddress": "No Address data",
            "IdImageLongLat": null,
            "IdImageLongLatTime": null,
            "ValidationExecuted": false,
            "Created": "2025-04-28T23:50:08.4709058+10:00",
            "IsUpdated": true,
            "Updated": null,
            "CreatedUser": "--",
            "UpdatedBy": "--"
          },
          {
            "IdImageBack": null,
            "HasBackImage": true,
            "DocumentIdImageValid": false,
            "DocumentIdReportType": 1,
            "Id": 0,
            "Selected": false,
            "IdIName": "PAN",
            "IdImage": null,
            "IdImageData": "No Location Info...",
            "IdImageLocationUrl": null,
            "Distance": null,
            "DistanceInMetres": null,
            "Duration": null,
            "DurationInSeconds": null,
            "IdImageLocationAddress": "No Address data",
            "IdImageLongLat": null,
            "IdImageLongLatTime": null,
            "ValidationExecuted": false,
            "Created": "2025-04-28T23:50:08.4709064+10:00",
            "IsUpdated": true,
            "Updated": null,
            "CreatedUser": "--",
            "UpdatedBy": "--"
          },
          {
            "IdImageBack": null,
            "HasBackImage": true,
            "DocumentIdImageValid": false,
            "DocumentIdReportType": 6,
            "Id": 0,
            "Selected": false,
            "IdIName": "BIRTH_CERTIFICATE",
            "IdImage": null,
            "IdImageData": "No Location Info...",
            "IdImageLocationUrl": null,
            "Distance": null,
            "DistanceInMetres": null,
            "Duration": null,
            "DurationInSeconds": null,
            "IdImageLocationAddress": "No Address data",
            "IdImageLongLat": null,
            "IdImageLongLatTime": null,
            "ValidationExecuted": false,
            "Created": "2025-04-28T23:50:08.4709073+10:00",
            "IsUpdated": true,
            "Updated": null,
            "CreatedUser": "--",
            "UpdatedBy": "--"
          },
          {
            "IdImageBack": null,
            "HasBackImage": true,
            "DocumentIdImageValid": false,
            "DocumentIdReportType": 8,
            "Id": 0,
            "Selected": false,
            "IdIName": "MEDICAL_CERTIFICATE",
            "IdImage": null,
            "IdImageData": "No Location Info...",
            "IdImageLocationUrl": null,
            "Distance": null,
            "DistanceInMetres": null,
            "Duration": null,
            "DurationInSeconds": null,
            "IdImageLocationAddress": "No Address data",
            "IdImageLongLat": null,
            "IdImageLongLatTime": null,
            "ValidationExecuted": false,
            "Created": "2025-04-28T23:50:08.4709079+10:00",
            "IsUpdated": true,
            "Updated": null,
            "CreatedUser": "--",
            "UpdatedBy": "--"
          },
          {
            "IdImageBack": null,
            "HasBackImage": true,
            "DocumentIdImageValid": false,
            "DocumentIdReportType": 4,
            "Id": 0,
            "Selected": false,
            "IdIName": "VOTER_CARD",
            "IdImage": null,
            "IdImageData": "No Location Info...",
            "IdImageLocationUrl": null,
            "Distance": null,
            "DistanceInMetres": null,
            "Duration": null,
            "DurationInSeconds": null,
            "IdImageLocationAddress": "No Address data",
            "IdImageLongLat": null,
            "IdImageLongLatTime": null,
            "ValidationExecuted": false,
            "Created": "2025-04-28T23:50:08.4709086+10:00",
            "IsUpdated": true,
            "Updated": null,
            "CreatedUser": "--",
            "UpdatedBy": "--"
          }
        ],
        "Questions": [
          {
            "Id": 0,
            "QuestionText": "Injury/Illness prior to commencement/revival ?",
            "AnswerText": null,
            "QuestionType": "dropdown",
            "Options": "YES, NO",
            "IsRequired": true,
            "ReportTemplateId": null,
            "ReportTemplate": null,
            "CaseQuestionnaireId": null,
            "CaseQuestionnaire": null,
            "Created": "2025-04-28T23:50:08.4718212+10:00",
            "IsUpdated": true,
            "Updated": null,
            "CreatedUser": "--",
            "UpdatedBy": "--"
          },
          {
            "Id": 0,
            "QuestionText": "Duration of treatment ?",
            "AnswerText": null,
            "QuestionType": "dropdown",
            "Options": "0 , Less Than 6 months, More Than 6 months",
            "IsRequired": true,
            "ReportTemplateId": null,
            "ReportTemplate": null,
            "CaseQuestionnaireId": null,
            "CaseQuestionnaire": null,
            "Created": "2025-04-28T23:50:08.4725888+10:00",
            "IsUpdated": true,
            "Updated": null,
            "CreatedUser": "--",
            "UpdatedBy": "--"
          },
          {
            "Id": 0,
            "QuestionText": "Name of person met at the cemetery",
            "AnswerText": null,
            "QuestionType": "text",
            "Options": null,
            "IsRequired": true,
            "ReportTemplateId": null,
            "ReportTemplate": null,
            "CaseQuestionnaireId": null,
            "CaseQuestionnaire": null,
            "Created": "2025-04-28T23:50:08.4725908+10:00",
            "IsUpdated": true,
            "Updated": null,
            "CreatedUser": "--",
            "UpdatedBy": "--"
          },
          {
            "Id": 0,
            "QuestionText": "Date and\u00A0time\u00A0of\u00A0death",
            "AnswerText": null,
            "QuestionType": "date",
            "Options": null,
            "IsRequired": true,
            "ReportTemplateId": null,
            "ReportTemplate": null,
            "CaseQuestionnaireId": null,
            "CaseQuestionnaire": null,
            "Created": "2025-04-28T23:50:08.4725916+10:00",
            "IsUpdated": true,
            "Updated": null,
            "CreatedUser": "--",
            "UpdatedBy": "--"
          }
        ],
        "Created": "2025-04-28T23:50:08.4666582+10:00",
        "IsUpdated": true,
        "Updated": null,
        "CreatedUser": "--",
        "UpdatedBy": "--"
      },
      {
        "Id": 0,
        "LocationName": "POLICE_ADDRESS",
        "AgentId": 2,
        "Agent": {
          "DigitalIdImageMatchConfidence": "",
          "Similarity": 0,
          "Has2Face": false,
          "IdImageValid": false,
          "ReportType": 0,
          "Id": 0,
          "Selected": false,
          "IdIName": null,
          "IdImage": null,
          "IdImageData": "No Location Info...",
          "IdImageLocationUrl": null,
          "Distance": null,
          "DistanceInMetres": null,
          "Duration": null,
          "DurationInSeconds": null,
          "IdImageLocationAddress": "No Address data",
          "IdImageLongLat": null,
          "IdImageLongLatTime": null,
          "ValidationExecuted": false,
          "Created": "2025-04-28T23:50:08.4727715+10:00",
          "IsUpdated": true,
          "Updated": null,
          "CreatedUser": "--",
          "UpdatedBy": "--"
        },
        "FaceIds": [],
        "DocumentIds": [
          {
            "IdImageBack": null,
            "HasBackImage": true,
            "DocumentIdImageValid": false,
            "DocumentIdReportType": 9,
            "Id": 0,
            "Selected": false,
            "IdIName": "POLICE_REPORT",
            "IdImage": null,
            "IdImageData": "No Location Info...",
            "IdImageLocationUrl": null,
            "Distance": null,
            "DistanceInMetres": null,
            "Duration": null,
            "DurationInSeconds": null,
            "IdImageLocationAddress": "No Address data",
            "IdImageLongLat": null,
            "IdImageLongLatTime": null,
            "ValidationExecuted": false,
            "Created": "2025-04-28T23:50:08.472783+10:00",
            "IsUpdated": true,
            "Updated": null,
            "CreatedUser": "--",
            "UpdatedBy": "--"
          }
        ],
        "Questions": [
          {
            "Id": 0,
            "QuestionText": "Cause of Death ?",
            "AnswerText": null,
            "QuestionType": "text",
            "Options": null,
            "IsRequired": true,
            "ReportTemplateId": null,
            "ReportTemplate": null,
            "CaseQuestionnaireId": null,
            "CaseQuestionnaire": null,
            "Created": "2025-04-28T23:50:08.4727856+10:00",
            "IsUpdated": true,
            "Updated": null,
            "CreatedUser": "--",
            "UpdatedBy": "--"
          },
          {
            "Id": 0,
            "QuestionText": "Name of Policeman met ?",
            "AnswerText": null,
            "QuestionType": "text",
            "Options": null,
            "IsRequired": true,
            "ReportTemplateId": null,
            "ReportTemplate": null,
            "CaseQuestionnaireId": null,
            "CaseQuestionnaire": null,
            "Created": "2025-04-28T23:50:08.4727864+10:00",
            "IsUpdated": true,
            "Updated": null,
            "CreatedUser": "--",
            "UpdatedBy": "--"
          },
          {
            "Id": 0,
            "QuestionText": "Was there any foul play ?",
            "AnswerText": null,
            "QuestionType": "dropdown",
            "Options": "YES, NO",
            "IsRequired": true,
            "ReportTemplateId": null,
            "ReportTemplate": null,
            "CaseQuestionnaireId": null,
            "CaseQuestionnaire": null,
            "Created": "2025-04-28T23:50:08.4727872+10:00",
            "IsUpdated": true,
            "Updated": null,
            "CreatedUser": "--",
            "UpdatedBy": "--"
          },
          {
            "Id": 0,
            "QuestionText": "Date time of Policeman met ?",
            "AnswerText": null,
            "QuestionType": "date",
            "Options": null,
            "IsRequired": true,
            "ReportTemplateId": null,
            "ReportTemplate": null,
            "CaseQuestionnaireId": null,
            "CaseQuestionnaire": null,
            "Created": "2025-04-28T23:50:08.472788+10:00",
            "IsUpdated": true,
            "Updated": null,
            "CreatedUser": "--",
            "UpdatedBy": "--"
          }
        ],
        "Created": "2025-04-28T23:50:08.4727699+10:00",
        "IsUpdated": true,
        "Updated": null,
        "CreatedUser": "--",
        "UpdatedBy": "--"
      },
      {
        "Id": 0,
        "LocationName": "HOSPITAL_ADDRESS",
        "AgentId": 3,
        "Agent": {
          "DigitalIdImageMatchConfidence": "",
          "Similarity": 0,
          "Has2Face": false,
          "IdImageValid": false,
          "ReportType": 0,
          "Id": 0,
          "Selected": false,
          "IdIName": null,
          "IdImage": null,
          "IdImageData": "No Location Info...",
          "IdImageLocationUrl": null,
          "Distance": null,
          "DistanceInMetres": null,
          "Duration": null,
          "DurationInSeconds": null,
          "IdImageLocationAddress": "No Address data",
          "IdImageLongLat": null,
          "IdImageLongLatTime": null,
          "ValidationExecuted": false,
          "Created": "2025-04-28T23:50:08.4727906+10:00",
          "IsUpdated": true,
          "Updated": null,
          "CreatedUser": "--",
          "UpdatedBy": "--"
        },
        "FaceIds": [],
        "DocumentIds": [
          {
            "IdImageBack": null,
            "HasBackImage": true,
            "DocumentIdImageValid": false,
            "DocumentIdReportType": 8,
            "Id": 0,
            "Selected": false,
            "IdIName": "MEDICAL_CERTIFICATE",
            "IdImage": null,
            "IdImageData": "No Location Info...",
            "IdImageLocationUrl": null,
            "Distance": null,
            "DistanceInMetres": null,
            "Duration": null,
            "DurationInSeconds": null,
            "IdImageLocationAddress": "No Address data",
            "IdImageLongLat": null,
            "IdImageLongLatTime": null,
            "ValidationExecuted": false,
            "Created": "2025-04-28T23:50:08.4727924+10:00",
            "IsUpdated": true,
            "Updated": null,
            "CreatedUser": "--",
            "UpdatedBy": "--"
          }
        ],
        "Questions": [
          {
            "Id": 0,
            "QuestionText": "Nature of death ?",
            "AnswerText": null,
            "QuestionType": "text",
            "Options": null,
            "IsRequired": true,
            "ReportTemplateId": null,
            "ReportTemplate": null,
            "CaseQuestionnaireId": null,
            "CaseQuestionnaire": null,
            "Created": "2025-04-28T23:50:08.4727936+10:00",
            "IsUpdated": true,
            "Updated": null,
            "CreatedUser": "--",
            "UpdatedBy": "--"
          },
          {
            "Id": 0,
            "QuestionText": "Name of Medical staff met ?",
            "AnswerText": null,
            "QuestionType": "text",
            "Options": null,
            "IsRequired": true,
            "ReportTemplateId": null,
            "ReportTemplate": null,
            "CaseQuestionnaireId": null,
            "CaseQuestionnaire": null,
            "Created": "2025-04-28T23:50:08.4727944+10:00",
            "IsUpdated": true,
            "Updated": null,
            "CreatedUser": "--",
            "UpdatedBy": "--"
          },
          {
            "Id": 0,
            "QuestionText": "Was there any foul play ?",
            "AnswerText": null,
            "QuestionType": "dropdown",
            "Options": "YES, NO",
            "IsRequired": true,
            "ReportTemplateId": null,
            "ReportTemplate": null,
            "CaseQuestionnaireId": null,
            "CaseQuestionnaire": null,
            "Created": "2025-04-28T23:50:08.4727952+10:00",
            "IsUpdated": true,
            "Updated": null,
            "CreatedUser": "--",
            "UpdatedBy": "--"
          },
          {
            "Id": 0,
            "QuestionText": "Date time of Medical staff  met ?",
            "AnswerText": null,
            "QuestionType": "date",
            "Options": null,
            "IsRequired": true,
            "ReportTemplateId": null,
            "ReportTemplate": null,
            "CaseQuestionnaireId": null,
            "CaseQuestionnaire": null,
            "Created": "2025-04-28T23:50:08.472796+10:00",
            "IsUpdated": true,
            "Updated": null,
            "CreatedUser": "--",
            "UpdatedBy": "--"
          }
        ],
        "Created": "2025-04-28T23:50:08.4727897+10:00",
        "IsUpdated": true,
        "Updated": null,
        "CreatedUser": "--",
        "UpdatedBy": "--"
      }
    ],
    "Basetemplate": false,
    "OriginalTemplateId": 1,
    "Created": "2025-04-28T13:50:08.4647012Z",
    "IsUpdated": true,
    "Updated": null,
    "CreatedUser": "--",
    "UpdatedBy": "system"
  }